#!/usr/bin/env bash

# https://github.com/conda/conda/issues/5165#issuecomment-665354035
NOW=$(date "+%Y-%m-%d")
CONDA_BASE=$(conda info --base)
CONDA_FUNCTION="etc/profile.d/conda.sh"
CONDA="$CONDA_BASE/$CONDA_FUNCTION"
source $CONDA

mkdir ./condaenvs-$NOW

ENVS=$(conda env list | grep '^\w' | cut -d' ' -f1)
for env in $ENVS; do
  conda activate $env
  conda env export --no-builds > ./condaenvs-$NOW/$env.yml
  echo "Exporting $env"
done
