#!/usr/bin/env bash
# adds all keys to ssh agent

# first activate the agent
eval "$(ssh-agent -s)"

# then iterate through ~/.ssh, ignoring *.pub, known_hosts and config
for key in ~/.ssh/*; do
    [[ $key == *.pub || $key == *known_hosts || $key == *config ]] && continue
    ssh-add $key
done

# https://serverfault.com/q/547923
bash -i
